### ISSUE TITLE
No Custom Keyboard Mapping

### ISSUE THREAD

**Issue by lloyd094** [ccseer/PinStack#4]
Using the Windows Store version, I am unable to map my custom shortcuts (for example, trying to remap either Ctrl+Alt+C or Ctrl+Alt+V to Ctrl+`) will not work correctly, resulting in nothing happening.

**Comment by ccseer** [comment]
are you sure about this?
I just tested it. It works fine.

I released Seer-1.9.0 weeks ago, I working on PinStack now

**Comment by lloyd094** [comment]
v.1.2.0 (via Windows Store): Just attempted again, and still does not work. Perhaps bugged?
